### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by mloenow** [a-rothwell/rivet-plugin-mongodb#2]
Hi!

I've encountered the following issue when attempting to install the plugin:

```
Installing plugin: MongoDB...
Checking for plugin updates: rivet-plugin-mongodb@latest
Removing existing plugin: rivet-plugin-mongodb@latest
Plugin not found locally or needs reinstall: rivet-plugin-mongodb@latest, downloading from NPM...
Downloading plugin tarball from NPM: https://registry.npmjs.org/rivet-plugin-mongodb/-/rivet-plugin-mongodb-0.0.3.tgz
Downloaded plugin tarball from NPM: https://registry.npmjs.org/rivet-plugin-mongodb/-/rivet-plugin-mongodb-0.0.3.tgz
Installing NPM dependencies...
 ENOENT  not found: node

This error happened while installing a direct dependency of /Users/ml/Library/Application Support/com.ironcladapp.rivet/plugins/rivet-plugin-mongodb-latest/package

pnpm: not found: node
    at getNotFoundError (/snapshot/dist/pnpm.cjs)
    at Function.whichSync [as sync] (/snapshot/dist/pnpm.cjs)
    at getCommandAbsolutePathSync (/snapshot/dist/pnpm.cjs)
    at Object.sync (/snapshot/dist/pnpm.cjs)
    at getSystemNodeVersionNonCached (/snapshot/dist/pnpm.cjs)
    at getSystemNodeVersionNonCached (/snapshot/dist/pnpm.cjs)
    at checkPackage (/snapshot/dist/pnpm.cjs)
    at packageIsInstallable (/snapshot/dist/pnpm.cjs)
    at resolveAndFetch (/snapshot/dist/pnpm.cjs)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Progress: resolved 1, reused 0, downloaded 0, added 0

Error installing plugin: Error installing plugin dependencies: rivet-plugin-mongodb@latest: 
```

It also happened with v0.0.2, unfortunately.

It seems like it's trying to build the package during the installation?

Let me know if you need any additional details from me.

**Comment by mloenow** [comment]
Installing it from source using the [steps outlined in the documentation](https://rivet.ironcladapp.com/docs/user-guide/plugins#installing-plugins-from-source) works fine.

**Comment by a-rothwell** [comment]
Hi,

So it works when running rivet from source, but not from the prebuilt rivet binaries?

Which version of the prebuilt binaries are you running?

**Comment by a-rothwell** [comment]
Or is it that it doesn't work when installed via the UI on the plugins page?

**Comment by mloenow** [comment]
Thanks for the swift reply!

The problem is that I cannot install it via the UI (plugins tab). I'm using Rivet 1.7.4. I can install the plugin from source, but I haven't had a chance to play around with it yet.

It's late here (CET), so I'll get back to you tomorrow hopefully.

BTW - how do I register the plugin so its nodes are recognized when running my graph from Node.js? Built-in plugins can be registered with `globalRivetNodeRegistry.registerPlugin(plugins.huggingFace);`, but it's not clear to me how I can do it with plugins installed from NPM.

**Comment by a-rothwell** [comment]
You would register it like this

```
import * as Rivet from '@ironclad/rivet-node'
import rivetPluginMongodb from "rivet-plugin-mongodb";

globalRivetNodeRegistry.registerPlugin(rivetPluginMongodb(Rivet));
```

And then you need to add the connection string in the plugin settings of the runGraph call
```
pluginSettings: {
      rivetPluginMongodb: {
        mongoDBConnectionString: env.RIVET_MONGODB_CONNECTION_STRING as string,
      }
    },
```

**Comment by mloenow** [comment]
Thanks. Will give it a try. Had an issue with typings, but I'll see if I can fix it.

**Comment by a-rothwell** [comment]
I was able to repro the issue with the prebuilt binaries version.
Going to open an issue with the core team.

**Comment by mloenow** [comment]
Thanks for opening the issue with core team!

I had some problems getting the plugin registered when using TypeScript due to missing type definitions, but I believe I have a fix for it. Submitting a pull request shortly 👍

**Comment by a-rothwell** [comment]
Thanks for submitting the PR!

Can you expand on the Type Errors you were getting?

**Comment by mloenow** [comment]
My TypeScript project complained that there were no type definitions when importing from the package. I had trouble compiling my project with `tsc` as well.

I can revert my changes locally if you need more details?

**Comment by a-rothwell** [comment]
All good, was just curious in case someone else runs into a similar type issue in the future.
I think the types stuff is good to merge.

I would like to try updating the bundle and package.json to match what the other plugins are now using. (Will expand on your PR)

@all-contributors please add mloenow for bugs

**Comment by mloenow** [comment]
Cool, sounds good. I would perhaps hold off releasing a new version until the issue in the Rivet app I linked to in the PR is resolved, as installing from source also doesn't work right now.

**Comment by a-rothwell** [comment]
When installing from source you could still manually checkout by tag.

**Comment by a-rothwell** [comment]
I think we're good to close this. Original issue should be fixed in V4 with the change to the package.json skipInstall option
